version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: movie_rating_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: movie_user
      POSTGRES_PASSWORD: movie_pass
      POSTGRES_DB: movie_db
    volumes:
      - movie_pgdata:/var/lib/postgresql/data

volumes:
  movie_pgdata:
